# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    # def __init__ (self):
    #   self.main_win = QMainWindow()
    #     self.bfs = Ui_MainWindow_BFS()
    #     self.uic.setupUi(self.main_win)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BFSButton = QtWidgets.QPushButton(self.centralwidget)
        self.BFSButton.setGeometry(QtCore.QRect(130, 210, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.BFSButton.setFont(font)
        self.BFSButton.setObjectName("BFSButton")
        self.UCSButton = QtWidgets.QPushButton(self.centralwidget)
        self.UCSButton.setGeometry(QtCore.QRect(130, 370, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.UCSButton.setFont(font)
        self.UCSButton.setObjectName("UCSButton")
        self.DFSButton = QtWidgets.QPushButton(self.centralwidget)
        self.DFSButton.setGeometry(QtCore.QRect(130, 290, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.DFSButton.setFont(font)
        self.DFSButton.setObjectName("DFSButton")
        self.ASButton = QtWidgets.QPushButton(self.centralwidget)
        self.ASButton.setGeometry(QtCore.QRect(130, 450, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.ASButton.setFont(font)
        self.ASButton.setObjectName("ASButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 40, 411, 121))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(42)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(420, 160, 831, 381))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("img/img1.jpg"))
        # self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tool Nhập môn trí tuệ nhân tạo"))
        self.BFSButton.setText(_translate("MainWindow", "Tool cho BFS"))
        self.UCSButton.setText(_translate("MainWindow", "Tool cho UCS"))
        self.DFSButton.setText(_translate("MainWindow", "Tool cho DFS"))
        self.ASButton.setText(_translate("MainWindow", "Tool cho A*"))
        self.label.setText(_translate("MainWindow", "XIN CHÀO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setStyleSheet("background-color: #930A48;")
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
